# c.f. https://dependabot.com/docs/config-file/
version: 1

update_configs:
  - package_manager: "go:modules"

    directory: "/"

    update_schedule: "daily"

    automerged_updates:
      - match:
          update_type: "semver:patch"
      - match:
          dependency_name: "github.com/stretchr/testify"
          update_type: "all"
      - match:
          dependency_name: "github.com/jarcoal/httpmock"
          update_type: "all"
      - match:
          dependency_name: "github.com/aws/aws-lambda-go"
          update_type: "semver:minor"

    default_assignees:
      - sue445
